BOT_TOKEN: 
  - MTAyMzIzNTg1MTE5NjU3OTg5MA.Gg0qzJ.gpXssz8yf8WYa9vdYLan6WujIDoQkSJDmQU7vg
CHANNEL_ID: 
  - 1059712693692551198
MODE: simsimi
REPLY: Y
SIMSIMI_LANG: en
DELAY: 35
DEL_AFTER: 
REPOST_LAST_CHAT: 100
