BOT_TOKEN: 
  - MTAyMzIzNTg1MTE5NjU3OTg5MA.GhWUAQ.ND23qjsqmwGNitdl_177sK_buHymPyySHzI8i8
CHANNEL_ID: 
  - 1059712693692551198
MODE: simsimi
REPLY: Y
SIMSIMI_LANG: en
DELAY: 35
DEL_AFTER: 
REPOST_LAST_CHAT: 100
