BOT_TOKEN: 
  - OTE4MDYxNzg0NjAxMDcxNjM2.G5lrfd.5dddbWBuOYv-C7pM35AQuz81rvZDW0L-c4Xdd8
CHANNEL_ID: 
  - 905273129918660678
MODE: simsimi
REPLY: Y
SIMSIMI_LANG: en
DELAY: 35
DEL_AFTER: 
REPOST_LAST_CHAT: 100
