BOT_TOKEN: 
  - MTAyMzIzNTg1MTE5NjU3OTg5MA.G4ZFjc.KtVBY
USOqKlr3dgHXyLftrDbfGXd0eJUeQONU4
CHANNEL_ID: 
  - 1063501843218567301
MODE: simsimi
REPLY: Y
SIMSIMI_LANG: en
DELAY: 35
DEL_AFTER: 
REPOST_LAST_CHAT: 100
