BOT_TOKEN: 
  - MTAyMzIzNTg1MTE5NjU3OTg5MA.GygjU3.deh4kw0tGf7Ebh5vGbOsG_OazEB-7aIdCsFIJE
CHANNEL_ID: 
  - 1032816068131041301
MODE: simsimi
REPLY: Y
SIMSIMI_LANG: en
DELAY: 35
DEL_AFTER: 
REPOST_LAST_CHAT: 100
